export default [
    {
        'os':'huya',
        'name':'虎牙直播',
        'download_name':'虎牙直播',
        'icon':'/static/os/huya_icon.png',
        'downUrl':'https://www.huya.com/download/',
        'linkUrl':'http://www.huya.com'
    },
    {
        'os':'douyu',
        'name':'斗鱼直播',
        'download_name':'斗鱼直播',
        'icon':'/static/os/douyu_icon.png',
        'downUrl':'https://www.douyu.com/client',
        'linkUrl':'https://www.douyu.com'
    },
    {
        'os':'xiongmao',
        'name':'熊猫直播',
        'download_name':'熊猫直播',
        'icon':'/static/os/xiongmao_icon.png',
        'downUrl':'https://www.panda.tv/client.html',
        'linkUrl':'https://www.panda.tv'
    },
    {
        'os':'longzhu',
        'name':'龙珠直播',
        'download_name':'龙珠直播(app下载)',
        'icon':'/static/os/longzhu_icon.png',
        'downUrl':'http://longzhu.com/app/download?from=fiappdownload',
        'linkUrl':'http://www.longzhu.com'
    },
    {
        'os':'yingke',
        'name':'映客直播',
        'download_name':'映客直播',
        'icon':'/static/os/yingke_icon.png',
        'downUrl':'http://www.inke.cn/',
        'linkUrl':'http://www.inke.cn/index.html'
    },
    {
        'os':'quanming',
        'name':'全民直播',
        'download_name':'全民直播',
        'icon':'/static/os/quanmin_icon.png',
        'downUrl':'https://www.quanmin.tv/static/pages/pc.html',
        'linkUrl':'https://www.quanmin.tv'
    },
    {
        'os':'qie',
        'name':'企鹅电竞',
        'download_name':'企鹅电竞',
        'icon':'/static/os/qie_icon.png',
        'downUrl':'http://egame.qq.com/download',
        'linkUrl':'http://egame.qq.com'
    },
    {
        'os':'chushou',
        'name':'触手直播',
        'download_name':'触手直播(app下载)',
        'icon':'/static/os/chushou_icon.png',
        'downUrl':'https://chushou.tv/download.htm',
        'linkUrl':'https://chushou.tv'
    },
    {
        'os':'bzhan',
        'name':'bilibili直播',
        'download_name':'bilibili直播(b站客户端app下载)',
        'icon':'/static/os/bilibili_icon.png',
        'downUrl':'https://app.bilibili.com/',
        'linkUrl':'https://live.bilibili.com/'
    },
    {
        'os':'kuaishou',
        'name':'快手直播',
        'download_name':'快手直播伴侣（主播工具）',
        'icon':'/static/os/kuaishou_icon.png',
        'downUrl':'https://www.kuaishou.com/kwai-live/',
        'linkUrl':'https://live.kuaishou.com/'
    },
    {
        'os':'yy',
        'name':'yy直播',
        'download_name':'yy直播',
        'icon':'/static/os/yy_icon.png',
        'downUrl':'http://www.yy.com/download',
        'linkUrl':'http://www.yy.com/'
    },{
        'os':'qianfan',
        'name':'千帆直播',
        'download_name':'千帆直播',
        'icon':'/static/os/qianfan_icon.png',
        'downUrl':'https://qf.56.com/help/download/',
        'linkUrl':'https://qf.56.com/'
    },
    {
        'os':'yi',
        'name':'一直播',
        'download_name':'一直播（点击有导航下载）',
        'icon':'/static/os/yi_icon.jpg',
        'downUrl':'http://www.yizhibo.com/',
        'linkUrl':'http://www.yizhibo.com/'
    },{
        'os':'liujianfang',
        'name':'6间房',
        'download_name':'6间房(app下载)',
        'icon':'/static/os/liujianfang_icon.png',
        'downUrl':'https://www.6.cn/',
        'linkUrl':'https://v.6.cn/event/liveClient/?t=phone'
    },{
        'os':'huajiao',
        'name':'花椒直播',
        'download_name':'花椒直播(右上角有下载按钮)',
        'icon':'/static/os/huajiao_icon.png',
        'downUrl':'http://www.huajiao.com/',
        'linkUrl':'https://v.6.cn/event/liveClient/?t=phone'
    },
    {
        'os':'zhanqi',
        'name':'战旗直播',
        'download_name':'战旗直播(右上角有下载按钮)',
        'icon':'/static/os/zhanqi_icon.png',
        'downUrl':'http://www.zhanqi.tv/',
        'linkUrl':'http://www.zhanqi.tv/'
    }, {
        'os':'huomao',
        'name':'火猫直播',
        'download_name':'火猫直播(底部有二维码下载)',
        'icon':'/static/os/huomao_icon.png',
        'downUrl':'https://www.huomao.com/',
        'linkUrl':'https://www.huomao.com/'
    }, {
        'os':'shihou',
        'name':'狮吼直播',
        'download_name':'狮吼直播(右上角有二维码下载)',
        'icon':'/static/os/shihou_icon.png',
        'downUrl':'http://www.shihou.tv/',
        'linkUrl':'http://www.shihou.tv/'
    },{
        'os':'qixiu',
        'name':'奇秀',
        'download_name':'奇秀(右上角有下载)',
        'icon':'/static/os/qixiu_icon.png',
        'downUrl':'http://x.pps.tv/',
        'linkUrl':'http://x.pps.tv/'
    },{
        'os':'KK',
        'name':'KK直播',
        'download_name':'KK直播(右上角有下载)',
        'icon':'/static/os/KK_icon.png',
        'downUrl':'http://www.kktv5.com/?channel!70281',
        'linkUrl':'http://www.kktv5.com/?channel!70281'
    },{
        'os':'woxiu',
        'name':'我秀',
        'download_name':'我秀(左下角有app下载)',
        'icon':'/static/os/woxiu_icon.png',
        'downUrl':'http://www.woxiu.com/',
        'linkUrl':'http://www.woxiu.com/'
    },{
        'os':'dawang',
        'name':'大王直播',
        'download_name':'大王直播(右上角有下载)',
        'icon':'/static/os/dawang_icon.png',
        'downUrl':'http://www.dawang.tv/',
        'linkUrl':'http://www.dawang.tv/'
    },
    // {
    //     'os':'feiyun',
    //     'name':'飞云直播',
    //     'download_name':'飞云直播(右上角有下载)',
    //     'icon':'/static/os/feiyun_icon.png',
    //     'downUrl':'http://www.feiyun.tv/',
    //     'linkUrl':'http://www.feiyun.tv/'
    // },




]